version: '3'
services:
  mysql1:
    image: mysql:5
    ports:
      - '13306:3306'
    volumes:
      - ./volumes/data/mysql1/:/var/lib/mysql
      - ./volumes/mysql1/conf.d:/etc/mysql/conf.d
      - ./volumes/mysql1/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  mysql2:
    image: mysql:5
    ports:
      - '13307:3306'
    volumes:
      - ./volumes/data/mysql2:/var/lib/mysql
      - ./volumes/mysql2/conf.d:/etc/mysql/conf.d
      - ./volumes/mysql2/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  etcd:
    image: bitnami/etcd
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ALLOW_NONE_AUTHENTICATION: 'yes'
