version: '3'
services:
  mysql1:
    image: mysql:5
    ports:
      - '13306:3306'
    volumes:
      - ./volumes/mysql1:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  mysql2:
    image: mysql:5
    ports:
      - '13307:3306'
    volumes:
      - ./volumes/mysql2:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
